baseURL: 'https://ubucon-asia.github.io/2021/'
languageCode: en-us
title: Ubucon Asia 2021
theme: ubuconasia
Paginate: 5
buildFuture: true
menu:
  main:
    - identifier: about
      name: About
      url: about
      weight: 1
    - identifier: sessions
      name: Sessions
      url: sessions
      weight: 2
    - identifier: sponsors
      name: Sponsors
      url: sponsors
      weight: 3
    - identifier: news
      name: News
      url: news
      weight: 4
    - identifier: wiki
      name: Wiki
      url: https://wiki.ubuntu.com/UbuconAsia/2021
      weight: 5
defaultContentLanguage: en
languages:
  ko:
    languageName: 한국어
    title: 우부콘 아시아 2021
    weight: 2
    contentDir: content/korean
    params:
      description: >-
        아시아 지역 우분투 LoCo 에서 준비한 첫 우분투 아시아 컨퍼런스.
      period: 2021년 3~4분기 중 개최 예정.
    menu:
      main:
        - identifier: about
          name: 소개
          url: about
          weight: 1
        - identifier: sessions
          name: 세션
          url: sessions
          weight: 2
        - identifier: sponsors
          name: 후원사
          url: sponsors
          weight: 3
        - identifier: news
          name: 소식
          url: news
          weight: 4
        - identifier: wiki
          name: 위키
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 5
  en:
    languageName: English
    title: Ubucon Asia 2021
    weight: 1
    contentDir: content/english
    params:
      description: >-
        The first Ubuntu Asia conference organized by Ubuntu LoCos in Asia.
      period: Expected to take place in 2021 Q3 or Q4
params:
  contact: sukso96100@gmail.com
  calendarOrganizer: Ubucon Asia 2021 Organizers
  calendarUidSuffix: 2021.asia.ubucon.org
outputs:
  section: ["HTML", "RSS", "Calendar"]