baseURL: 'https://2021.ubucon.asia/'
languageCode: en-us
title: Ubucon Asia 2021
theme: ubuconasia
Paginate: 5
buildFuture: true
enableRobotsTXT: true
menu:
  main:
    - identifier: about
      name: About
      url: about
      weight: 1
    - identifier: sessions
      name: Sessions
      url: sessions
      weight: 2
    - identifier: sponsors
      name: Sponsors
      url: sponsors
      weight: 3
    - identifier: news
      name: News
      url: news
      weight: 4
    - identifier: wiki
      name: Wiki
      url: https://wiki.ubuntu.com/UbuconAsia/2021
      weight: 5
defaultContentLanguage: en
languages:
  ko:
    languageName: 한국어
    title: 우부콘 아시아 2021
    weight: 2
    params:
      description: >-
        아시아에 있는 다양한 우분투 지역 커뮤니티에서 준비한 첫 우분투 아시아 컨퍼런스.
      period: 2021년 9월 25일 ~ 26일
    menu:
      main:
        - identifier: about
          name: 소개
          url: about
          weight: 1
        - identifier: sessions
          name: 세션
          url: sessions
          weight: 2
        - identifier: sponsors
          name: 후원사
          url: sponsors
          weight: 3
        - identifier: news
          name: 소식
          url: news
          weight: 4
        - identifier: wiki
          name: 위키
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 5
  en:
    languageName: English
    title: Ubucon Asia 2021
    weight: 1
    params:
      description: >-
        The first Ubuntu Asia conference organized by Ubuntu Local Communities in Asia.
      period: September 25th ~ 26th, 2021 
  id:
    languageName: Bahasa Indonesia
    title: Ubucon Asia 2021
    weight: 2
    params:
      description: >-
        Konferensi Ubuntu Asia pertama yang diselenggarakan oleh Komunitas Lokal Ubuntu di Asia.
      period: Diharapkan berlangsung pada 2021 Q3 atau Q4
    menu:
      main:
        - identifier: about
          name: Tentang
          url: about
          weight: 1
        - identifier: sessions
          name: Sesi
          url: sessions
          weight: 2
        - identifier: sponsors
          name: Sponsor
          url: sponsors
          weight: 3
        - identifier: news
          name: Berita
          url: news
          weight: 4
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 5
  ja:
    languageName: 日本語
    title: Ubucon Asia 2021
    weight: 3
    params:
      description: >-
        アジアのUbuntuコミュニティが集結する、アジア地域初のUbuntuカンファレンス開催
      period: 2021年 第3〜4四半期に開催準備中
    menu:
      main:
        - identifier: about
          name: Ubucon Asiaとは
          url: about
          weight: 1
        - identifier: sessions
          name: セッション
          url: sessions
          weight: 2
        - identifier: sponsors
          name: スポンサー
          url: sponsors
          weight: 3
        - identifier: news
          name: ニュース
          url: news
          weight: 4
        - identifier: wiki
          name: Wiki
          url: https://wiki.ubuntu.com/UbuconAsia/2021
          weight: 5
params:
  contact: contact@ubucon.asia
  calendarOrganizer: Ubucon Asia 2021 Organizers
  calendarUidSuffix: 2021.asia.ubucon.org
  facebook: ubuconasia
  twitter: ubuconasia
  github: ubucon-asia
  repo: https://github.com/ubucon-asia/2021
  copyright:  >-
    © 2021 Ubucon Asia 2021 Website authors.
    Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY 4.0. 
    Ubuntu and Canonical are registered trademarks of Canonical Ltd.
  email: contact@ubucon.asia
outputs:
  section: ["HTML", "RSS", "Calendar"]
