baseURL: 'https://2021.ubucon.asia/'
languageCode: en-us
title: Ubucon Europe 2022
theme: ubuconasia
Paginate: 5
buildFuture: true
enableRobotsTXT: true

defaultContentLanguage: en
languages:
  en:
    languageName: English
    title: Ubucon Europe 2022
    weight: 1
    params:
      description: >-
        Conference for Ubuntu - an open source, community-driven and free linux distribution -
        and other free and open source technologies.
        Ubucon is an event organized by the Ubuntu Communities from all around the world.
      period: "Date: to be announced..."
    menu:
      main:
        - identifier: about
          name: About
          url: about
          weight: 1
        - identifier: hosts
          name: Hosts
          url: hosts
          weight: 2
        - identifier: programs-group
          name: Programs
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: Sessions
          url: sessions
          weight: 3
        - identifier: venue
          parent: programs-group
          name: Virtual venue(Gather town)
          url: venue
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Confirmed sessions
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: Sponsors/Patrons
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: Sponsors
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Individual patrons
          url: patrons
          weight: 4
        - identifier: news
          name: News
          url: news
          weight: 5

  pt:
    languageName: Português
    title: Ubucon Europe 2022
    weight: 1
    params:
      description: >-
        Conferência dedicada ao Ubuntu - uma distribuição de linux livre,
        de código aberto e orientado à comunidade -
        e outras tecnologias livres e de código aberto.
        A Ubucon é um evento organizado pelas comunidades de Ubuntu de todo o mundo.
      period: "Data: a definir..."
    menu:
      main:
        - identifier: about
          name: Sobre
          url: about
          weight: 1
        - identifier: hosts
          name: Organizadores
          url: hosts
          weight: 2
        - identifier: programs-group
          name: Programa
          url: programs
          weight: 3
        - identifier: sessions
          parent: programs-group
          name: Sessões
          url: sessions
          weight: 3
        - identifier: venue
          parent: programs-group
          name: Espaço Virtual (Gather town)
          url: venue
          weight: 3
        - identifier: confirmed
          parent: programs-group
          name: Sessões confirmadas
          url: confirmed
          weight: 3
        - identifier: sponsors-group
          name: Patrocínios
          url: sponsors
          weight: 4
        - identifier: sponsors
          parent: sponsors-group
          name: Patrocinadores
          url: sponsors
          weight: 4
        - identifier: patrons
          parent: sponsors-group
          name: Doações individuais
          url: patrons
          weight: 4
        - identifier: news
          name: Notícias
          url: news
          weight: 5

params:
  contact: contact@ubucon.org
  calendarOrganizer: Ubucon Europe 2022 Organizers
  calendarUidSuffix: 2022.europe.ubucon.org
  facebook: UbuconEurope # check for ownership
  twitter: ubuconEurope
  github: ubuconeurope
  repo: https://github.com/ubuconeurope/website-2022
  copyright:  >-
    © 2021 Ubucon Europe 2022 Website authors.
    Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY 4.0.
    Ubuntu and Canonical are registered trademarks of Canonical Ltd.
  email: contact@ubucon.org
  registerURLs:
    attendee: /cfs
    callForSpeakers: /cfs
  timetable:
    dateStart: 2021-09-25T12:00:00+09:00
    dateEnd: 2021-09-26T22:00:00+09:00
    timeStart: 2000-01-01T13:00:00+09:00 # Use random date for timeStart param
outputs:
  section: ["HTML", "RSS"]

markup:
  goldmark:
    renderer:
      unsafe: true